version: "3.9"

services:
    match_maker:
        container_name: ${HTTP_SERVER_NAME}
        build: .
        ports:
            - ${HTTP_SERVER_PORT}:8081
        depends_on:
            - match_maker_db
            - match_maker_redis
        environment:
            ENV: ${ENV_TYPE}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_DRIVER_NAME: ${DB_DRIVER_NAME}
            DB_USER_NAME: ${DB_USER_NAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_SSL_MODE: ${DB_SSL_MODE}
            DB_MAX_CONNS: ${DB_MAX_CONNS}
            HTTP_SERVER_TIMEOUT: ${HTTP_SERVER_TIMEOUT}
            HTTP_SERVER_IDLE_TIMEOUT: ${HTTP_SERVER_IDLE_TIMEOUT}
            HTTP_SERVER_PORT: ${HTTP_SERVER_PORT}
            HTTP_SERVER_NAME: ${HTTP_SERVER_NAME}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_DB: ${REDIS_DB}
            REMAINING_USERS_KEY: ${REMAINING_USERS_KEY}

    match_maker_db:
        restart: always
        container_name: ${DB_NAME}
        image: postgres:latest
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            POSTGRES_USER: ${DB_USER_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}

    match_maker_redis:
        container_name: ${REDIS_NAME}
        image: redis:alpine
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        command: >
            --requirepass ${REDIS_PASSWORD}