version: "3.9"

services:
    match_maker:
        container_name: ${HTTP_SERVER_NAME}
        build: .
        ports:
            - ${HTTP_SERVER_PORT}:8081
        depends_on:
            - match_maker_db
        environment:
            ENV: ${ENV_TYPE}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_DRIVER_NAME: ${DB_DRIVER_NAME}
            DB_USER_NAME: ${DB_USER_NAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_SSL_MODE: ${DB_SSL_MODE}
            DB_MAX_CONNS: ${DB_MAX_CONNS}
            HTTP_SERVER_TIMEOUT: ${HTTP_SERVER_TIMEOUT}
            HTTP_SERVER_IDLE_TIMEOUT: ${HTTP_SERVER_IDLE_TIMEOUT}
            HTTP_SERVER_PORT: ${HTTP_SERVER_PORT}
            HTTP_SERVER_NAME: ${HTTP_SERVER_NAME}

    match_maker_db:
        restart: always
        container_name: ${DB_NAME}
        image: postgres:latest
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            POSTGRES_USER: ${DB_USER_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}